build:
  maxIssues: 0

config:
  validation: true

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: true
  CyclomaticComplexMethod:
    threshold: 15

style:
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '100']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    allowedNames: '.*Preview'
  WildcardImport:
    active: true
  ReturnCount:
    max: 3
    excludeGuardClauses: true
  MaxLineLength:
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable', 'Preview']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Z0-9]*'

coroutines:
  active: true
